import os

# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE

# READ README FOR CONFIG


class Config(object):
    # get a token from @BotFather
    TG_BOT_TOKEN = os.environ.get("TG_BOT_TOKEN", "1441021551:AAHZ7_QBH8gtrV2_6qPmsx_ocqshIqMnsYk")
    # The Telegram API things
    APP_ID = int(os.environ.get("APP_ID", 1760875))
    API_HASH = os.environ.get("API_HASH", "1cf39a758fd1abd6744561563f158ff3")
    OWNER_ID = int(os.environ.get("OWNER_ID", 1004538768))
    # Get these values from my.telegram.org
    # to store the channel ID who are authorized to use the bot
    AUTH_CHANNEL = set(int(x) for x in os.environ.get("AUTH_CHANNEL", "-1001186041542 -1001491078689 1327934109 1054316613 1152240399").split())
    # the download location, where the HTTP Server runs
    DOWNLOAD_LOCATION = "./DOWNLOADS"
    # Telegram maximum file upload size
    MAX_FILE_SIZE = 50000000
    TG_MAX_FILE_SIZE = 2097152000
    FREE_USER_MAX_FILE_SIZE = 50000000
    # chunk size that should be used with requests
    CHUNK_SIZE = int(os.environ.get("CHUNK_SIZE", 128))
    # default thumbnail to be used in the videos
    DEF_THUMB_NAIL_VID_S = os.environ.get("DEF_THUMB_NAIL_VID_S", "https://telegra.ph/file/b0526eab13658ff5e2123.jpg")
    # maximum message length in Telegram
    MAX_MESSAGE_LENGTH = 4096
    # set timeout for subprocess
    PROCESS_MAX_TIMEOUT = 3600
    #
    SP_LIT_ALGO_RITH_M = os.environ.get(
        "SP_LIT_ALGO_RITH_M",
        "hjs"
    )
    ARIA_TWO_STARTED_PORT = int(os.environ.get("ARIA_TWO_STARTED_PORT", 6800))
    EDIT_SLEEP_TIME_OUT = int(os.environ.get("EDIT_SLEEP_TIME_OUT", 15))
    MAX_TIME_TO_WAIT_FOR_TORRENTS_TO_START = int(os.environ.get("MAX_TIME_TO_WAIT_FOR_TORRENTS_TO_START", 600))
    MAX_TG_SPLIT_FILE_SIZE = int(os.environ.get("MAX_TG_SPLIT_FILE_SIZE", 2097152000))
    # add config vars for the display progress
    FINISHED_PROGRESS_STR = os.environ.get("FINISHED_PROGRESS_STR", "⬢")
    UN_FINISHED_PROGRESS_STR = os.environ.get("UN_FINISHED_PROGRESS_STR", "⬡")
    # add offensive API
    TG_OFFENSIVE_API = os.environ.get("TG_OFFENSIVE_API", None)
    CUSTOM_FILE_NAME = os.environ.get("CUSTOM_FILE_NAME", "")
    LEECH_COMMAND = os.environ.get("LEECH_COMMAND", "getfile@AiTorrentWare3_Bot")
    YTDL_COMMAND = os.environ.get("YTDL_COMMAND", "utube@AiTorrentWare3_Bot")
    RCLONE_CONFIG = os.environ.get("RCLONE_CONFIG", """type = drive
client_id = 348454245101-jdjl3q3n2fkj6kdpn2neemnp38vnca3t.apps.googleusercontent.com
client_secret = nBtA-uAwg7kuOr4SsUxpbMqJ
scope = drive
root_folder_id = 0AP2XvXH_hQlDUk9PVA
token = {"access_token":"ya29.a0AfH6SMDyMhAYBH4S-rjo9qbwtLwox_W1lslUT1uWM0zdc2V6KK_RnnqOM1t2QEU8ZSP_RZfN-pvdxYO1WSpEaUhg
_SlsdYUbkRFA4Xqn9z9wyeQiI-tVKnAyz5VArSWImkJCbdgBoVtO6tUW2H3h93Kia0hw9uFhX9QB9iDQRnY","token_type":"Bearer","refresh_toke
n":"1//0gn_3eR88M0tyCgYIARAAGBASNwF-L9IrRVj2sovWiayGtdW-uFy8quQDN312PMqTISKsQpEkSyHp-OvZ30evnBO66BJ2I78x_20","expiry":"2
020-12-28T12:45:06.0593623+05:30"}
team_drive = 0AP2XvXH_hQlDUk9PVA""")
    DESTINATION_FOLDER = os.environ.get("DESTINATION_FOLDER", "AiTorrentWare3_Bot")
    GLEECH_COMMAND = os.environ.get("GLEECH_COMMAND", "loadlink@AiTorrentWare3_Bot")
    INDEX_LINK = os.environ.get("INDEX_LINK", "https://bot.aitorrentware.workers.dev/AiTorrentWare3_Bot")
    TELEGRAM_LEECH_COMMAND_G = os.environ.get("TELEGRAM_LEECH_COMMAND_G", "loadfile@AiTorrentWare3_Bot")
    CANCEL_COMMAND_G = os.environ.get("CANCEL_COMMAND_G", "cancel")
    GET_SIZE_G = os.environ.get("GET_SIZE_G", "getsize@AiTorrentWare3_Bot")
    STATUS_COMMAND = os.environ.get("STATUS_COMMAND", "sts@AiTorrentWare3_Bot")
    SAVE_THUMBNAIL = os.environ.get("SAVE_THUMBNAIL", "setpic@AiTorrentWare3_Bot")
    CLEAR_THUMBNAIL = os.environ.get("CLEAR_THUMBNAIL", "delpic@AiTorrentWare3_Bot")
    UPLOAD_AS_DOC = os.environ.get("UPLOAD_AS_DOC", "True")
    PYTDL_COMMAND_G = os.environ.get("PYTDL_COMMAND_G", "utube@AiTorrentWare3_Bot")
    LOG_COMMAND = os.environ.get("LOG_COMMAND", "log@AiTorrentWare3_Bot")
    CLONE_COMMAND_G = os.environ.get("CLONE_COMMAND_G", "getclone@AiTorrentWare3_Bot")
    UPLOAD_COMMAND = os.environ.get("UPLOAD_COMMAND", "upload@AiTorrentWare3_Bot")
    RENEWME_COMMAND = os.environ.get("RENEWME_COMMAND", "renewme")
